micronaut:
  application:
    name: micronaut-person

datasources:
    default:
        url: ${db_url:`jdbc:mysql://localhost:3306/test`}
        username: ${db_user:root}
        password: ${db_password:`!qaz@wsx`}
        driverClassName: ${db_driver:com.mysql.cj.jdbc.Driver}
        dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
        show_sql: false
        
graphql:
  enabled: true 
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql