micronaut:
  application:
    name: micronaut-person
jackson:
  bean-introspection-module: true
---
datasources:
    default:
        url: ${db_url:`jdbc:mysql://localhost:3306/test`}
        username: ${db_user:root}
        password: ${db_password:`!qaz@wsx`}
        driverClassName: ${db_driver:org.mariadb.jdbc.Driver}
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
---        
graphql:
  enabled: true 
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql